# Generated by Django 3.0 on 2020-01-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='프포필이미지'),
        ),
    ]
