# Generated by Django 2.2.10 on 2020-02-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img_profile',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='프로필이미지'),
        ),
    ]
